name = 'SeeDAO Online'

modules = [
    './main',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad'
]

[start]
    map = 'node-consensus-conference'
    graphic = 'hero'
    hitbox = [16, 16]